y-operator/helmrelease.yaml:

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  releaseName: opentelemetry-operator
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.64.0" # Проверь актуальную версию
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  interval: 5m
