# Уменьшаем реплики демо-приложения
apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-version-api
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-version-data
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: data
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-version-front
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: front
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-version-img
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: img
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
# Удаляем старый ingress
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador
  namespace: default
