apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-version-api
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-version-data
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-version-front
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: front
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-version-img
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: img
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
