apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: default
data:
  local-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    limits_config:
      ingestion_rate_mb: 20
      max_streams_per_user: 10000
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
