{
 "title": "Demo Logs & Metrics",
 "tags": [
  "demo",
  "monitoring",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Container error",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} |= \"level=error\""
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[2m])) by (pod)"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total"
    }
   ]
  },
  {
   "title": "Network Transmit (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container!=\"\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network Receive (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container!=\"\"}[1m])) by (pod)"
    }
   ]
  }
 ]
}