apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 1m
  path: "./manifests"   # путь к директории с Kubernetes-манифестами
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-stack
    namespace: flux-system
  targetNamespace: default   # здесь укажи namespace для ресурсов
