apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-09-20T10:11:05Z"
  labels:
    kustomize.toolkit.fluxcd.io/name: monitoring-stack
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: grafana
  namespace: default
  resourceVersion: "1758411123779679019"
  uid: a41b4d4a-d0eb-4c5e-aa14-1b94afeb5d49
spec:
  clusterIP: 34.118.226.163
  clusterIPs:
  - 34.118.226.163
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
